/*
 * This file was automatically generated by EvoSuite
 * Thu May 04 09:07:38 GMT 2023
 */

package com.example.task_evaluated;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.task_evaluated.task_17820;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class task_17820_ESTest extends task_17820_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      task_17820 task_17820_0 = new task_17820();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      try { 
        task_17820.getLinkName("9[4");
      } catch(IOException e) {
         //
         // An I/O exception occurred while opening a connection to the URL: no protocol: 9[4
         //
         verifyException("com.example.task_evaluated.task_17820", e);
      }
  }
}
